require 'rspec/core/rake_task'
require 'rubocop/rake_task'
require 'foodcritic'

begin
  require 'kitchen/rake_tasks'
  Kitchen::RakeTasks.new
rescue LoadError
  puts '>>>>> Kitchen gem not loaded, omitting tasks' unless ENV['CI']
end

RuboCop::RakeTask.new(:rubocop)

FoodCritic::Rake::LintTask.new(:foodcritic)

RSpec::Core::RakeTask.new(:chefspec)

task default: [:rubocop, :foodcritic, :chefspec]
